CREATE TABLE IF NOT EXISTS "films" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "release_date" date NOT NULL,
  "duration" integer NOT NULL,
  "rating_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL UNIQUE,
  "login" varchar NOT NULL UNIQUE,
  "name" varchar NOT NULL,
  "birthday" date
);

CREATE TABLE IF NOT EXISTS "friendship" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "friend_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "genre" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_genre" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "film_id" integer NOT NULL,
  "genre_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_likes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "film_id" integer NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "rating_mpa" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" ENUM('G', 'PG', 'PG-13', 'R', 'NC-17') NOT NULL
);

CREATE TABLE IF NOT EXISTS "directors" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_directors" (
    "film_id" integer REFERENCES "films" ("id") ON DELETE CASCADE,
    "director_id" integer REFERENCES "directors" ("id") ON DELETE CASCADE,
    PRIMARY KEY ("film_id", "director_id")
);

ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "rating_mpa" ("id");

ALTER TABLE "friendship" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "friendship" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "film_genre" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "film_likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id") ON DELETE CASCADE;

ALTER TABLE "film_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;


